stages:
#  - test
  - deploy

variables:
  PLUGIN_PATH: "lib/editor/atto/plugins/wordcount/"
  PLUGIN_NAME: wordcount

include:
  - project: '715-scrum1/grp_moodle/ci-cd-templates'
    file:
    #  - 'moodle-plugin-ci.yml'
      - 'deploy.yml'
