stages:
  - test
  - deploy

variables:
  PLUGIN_PATH: "lib/editor/atto/plugins/wordcount/"


variabletest:
  stage: deploy
  script:
   - echo $TEST_VARIABLE
   - echo $read_only_token
   - echo $READ_ONLY_TOKEN
