stages:
#  - test
  - deploy

variables:
  PLUGIN_PATH: "lib/editor/atto/plugins/wordcount/"
  PLUGIN_NAME: "wordcount"

#include:
#  - project: '715-scrum1/grp_moodle/ci-cd-templates'
#    file:
#      - 'moodle-plugin-ci.yml'
#      - 'deploy-dev.yml'


update_ansible:
  stage: deploy
  before_script:
    - 'command -v git >/dev/null || ( apt-get update -y && apt-get install git -y )'
    - wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    - chmod a+x yq
  script:
    - git clone https://gitlab-ci-token:${DEPLOYMENT_READ_WRITE}@gitlab.uni-graz.at/715-scrum1/grp_moodle/deployment.git
    - cd deployment
    - git checkout -b deployment_test
    - yq -i '(.internal_plugins.[] | select(.name == "${PLUGIN_NAME}")).version = "${CI_COMMIT_SHORT_SHA}"' plugins/config/inhouse_plugins.yml
    - git add plugins/config/inhouse_plugins.yml
    - git commit -m "nur ein deployment test"
    - git push
  when: manual
