stages:
  - test
  - deploy

variables:
  PLUGIN_PATH: "lib/editor/atto/plugins/"
  PLUGIN_NAME: wordcount

include:
  - project: '715-scrum1/grp_moodle/ci-cd-templates'
    file:
      - 'moodle-plugin-ci.yml'
      - 'deploy.yml'

# Overide Moodle Branches, this version only works with Moodle 4.0
# For Moodle 3.11+ see other uniGraz/MOOBLE_311_STABLE branch
moodle_plugin_ci:
  parallel:
    matrix:
      - MOODLE_BRANCH: [ MOODLE_400_STABLE]
        MOODLE_PHP_IMAGE: ["moodlehq/moodle-php-apache:7.4"]
        POSTGRES_IMAGE: ["postgres:14-alpine"]
