stages:
  - test
  - deploy

variables:
  PLUGIN_PATH: "lib/editor/atto/plugins/wordcount/"

include:
  # - project: '715-scrum1/grp_moodle/continuous-integration'
  #   file: '.gitlab-ci-template-one-job-only.yml'
  - project: '715-scrum1/grp_moodle/continuous-integration'
    file: '.gitlab-ci-deploy-dev.yml'
